//! Forces ts-rs to emit `src/types/ipc.generated.ts` during `cargo test`.
//!
//! Each `#[derive(TS)]` type is composed into one file here (rather than using
//! per-type `#[ts(export)]`, which races on a shared output path). Run via the
//! npm `prebuild` / `gen-types` script.

use server_supervisor_lib::settings::Settings;
use server_supervisor_lib::types::{ProcInfo, ProcStatus};
use std::fs;
use std::path::PathBuf;
use ts_rs::TS;

const HEADER: &str = "// This file is auto-generated by `cargo test --test export_types`.\n// Do not edit manually.\n\n";

fn output_path() -> PathBuf {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest_dir
        .join("..")
        .join("src")
        .join("types")
        .join("ipc.generated.ts")
}

fn decl<T: TS + 'static + ?Sized>() -> String {
    format!("export {}\n", T::decl())
}

#[test]
fn emit_ipc_types() {
    let mut out = String::from(HEADER);
    out.push_str(&decl::<ProcStatus>());
    out.push_str(&decl::<ProcInfo>());
    out.push_str(&decl::<Settings>());

    let path = output_path();
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).expect("create parent dir for ipc.generated.ts");
    }
    fs::write(&path, out).expect("write ipc.generated.ts");
}
